//
// Created by PinkySmile on 12/03/2022.
//

#ifndef SOFGV_VERSION_H
#define SOFGV_VERSION_H


#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_BUILD 0
#define VERSION_PATCH 0

#define VERSION_DIGITS VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_PATCH
#define REAL_VERSION_STR "beta 1.0"
#ifdef _DEBUG
#define VERSION_STR REAL_VERSION_STR" DEBUG"
#else
#define VERSION_STR REAL_VERSION_STR
#endif
#define REPLAY_MAGIC 0xF153E8DC

unsigned getMagic();


#endif //SOFGV_VERSION_H
